### ISSUE TITLE
Error while getting a list of labels from the annotations.json

### ISSUE THREAD

**Issue by Javokhir169** [cloud-annotations/google-colab-training#1]
Every time when I run all cells for training I get an error during generating a Label Map.
`ConnectionAbortedError                    Traceback (most recent call last)
<ipython-input-24-c4e576bbbe64> in <module>()
      4 # Get a list of labels from the annotations.json
      5 labels = {}
----> 6 with open(ANNOTATIONS_JSON_PATH) as f:
      7   annotations = json.load(f)
      8   labels = annotations['labels']

ConnectionAbortedError: [Errno 103] Software caused connection abort: '/content/8.candels/_annotations.json'`

Can anybody help?

**Comment by bourdakos1** [comment]
I wonder if it’s because your bucket name is “8.candels” it might not like the “.”

Can you try changing CLOUD_ANNOTATIONS_MOUNT to something like “/content/bucket”

**Comment by Javokhir169** [comment]
> I wonder if it’s because your bucket name is “8.candels” it might not like the “.”
> 
> Can you try changing CLOUD_ANNOTATIONS_MOUNT to something like “/content/bucket”

Thank you for your reply. I tried to change CLOUD_ANNOTATIONS_MOUNT as you suggest but it did not worked out. After I created a new project with the correct name and it works fine
